GoPro Synchronization Tool
UCSD-E4E/fishsense-tools pull request #1
Opened 2023-06-02 19:40 UTC by Xeanies

Created Gopro sync tool and would like for it to be added to the fishsense-tools repository.

2023-06-05 22:48 UTC, ntlhui requested changes
I'm getting some weird test case behavior.  I am using this video: https://photos.app.goo.gl/5Z6Ctz9Bzv1D8RibA.  I them use ffmpeg to trim the first 2 seconds from the video (resulting is the last 8 seconds of the original).  I then use that for left and right.  The output videos have a different aspect ratio (view is squashed), and I only have the data after the clap.  Is this the intended behavior?  It would seem better for this to only trim out the non-common time segment.

2023-06-05 22:48 UTC, ntlhui commented on Gopro-Sync/goprosync.py
> +    curr_directory = Path(os.getcwd()).joinpath(".temp")
Simpler to do this:
```
curr_directory = Path('.temp')
curr_directory.mkdir(exists_ok=True)
```

2023-06-05 22:48 UTC, ntlhui commented on Gopro-Sync/goprosync.py
> +        pass
Simpler to use `shutil`
```
shutil.rmtree(curr_directory)
```

2023-06-05 22:48 UTC, ntlhui commented on Gopro-Sync/goprosync.py
> +
Extra newlines

2023-06-05 22:48 UTC, ntlhui commented on .gitignore
Use https://github.com/UCSD-E4E/python-repo-example/blob/main/.gitignore and add all appropriate additional ignores

2023-06-05 22:48 UTC, ntlhui commented on Gopro-Sync/goprosync.py
```
fishsense-tools\Gopro-Sync> pylint .\goprosync.py
************* Module goprosync
goprosync.py:6:40: C0303: Trailing whitespace (trailing-whitespace)
goprosync.py:14:0: C0303: Trailing whitespace (trailing-whitespace)
goprosync.py:19:0: C0303: Trailing whitespace (trailing-whitespace)
goprosync.py:49:0: C0303: Trailing whitespace (trailing-whitespace)
goprosync.py:53:0: C0303: Trailing whitespace (trailing-whitespace)
goprosync.py:56:0: C0303: Trailing whitespace (trailing-whitespace)
goprosync.py:63:59: C0303: Trailing whitespace (trailing-whitespace)
goprosync.py:92:0: C0301: Line too long (102/100) (line-too-long)
goprosync.py:93:0: C0301: Line too long (137/100) (line-too-long)
goprosync.py:98:40: C0303: Trailing whitespace (trailing-whitespace)
goprosync.py:115:0: C0303: Trailing whitespace (trailing-whitespace)
goprosync.py:129:0: C0303: Trailing whitespace (trailing-whitespace)
goprosync.py:133:0: C0303: Trailing whitespace (trailing-whitespace)
goprosync.py:137:0: C0303: Trailing whitespace (trailing-whitespace)
goprosync.py:143:0: C0303: Trailing whitespace (trailing-whitespace)
goprosync.py:147:0: C0303: Trailing whitespace (trailing-whitespace)
goprosync.py:151:0: C0301: Line too long (104/100) (line-too-long)
goprosync.py:157:0: C0305: Trailing newlines (trailing-newlines)
goprosync.py:1:0: C0114: Missing module docstring (missing-module-docstring)
goprosync.py:11:0: C0116: Missing function or method docstring (missing-function-docstring)
goprosync.py:11:0: R0914: Too many local variables (37/15) (too-many-locals)
goprosync.py:60:11: W0718: Catching too general exception Exception (broad-exception-caught)
goprosync.py:88:4: C0103: Variable name "m" doesn't conform to snake_case naming style (invalid-name)
goprosync.py:11:0: R0915: Too many statements (59/50) (too-many-statements)
goprosync.py:114:0: C0116: Missing function or method docstring (missing-function-docstring)
goprosync.py:128:8: R1722: Consider using 'sys.exit' instead (consider-using-sys-exit)
goprosync.py:132:8: R1722: Consider using 'sys.exit' instead (consider-using-sys-exit)
goprosync.py:136:8: R1722: Consider using 'sys.exit' instead (consider-using-sys-exit)
goprosync.py:142:8: R1722: Consider using 'sys.exit' instead (consider-using-sys-exit)
goprosync.py:146:8: R1722: Consider using 'sys.exit' instead (consider-using-sys-exit)
goprosync.py:5:0: C0411: standard import "import os" should be placed before "import numpy as np" (wrong-import-order)
goprosync.py:7:0: C0411: standard import "from pathlib import Path" should be placed before "import numpy as np" (wrong-import-order)
goprosync.py:8:0: C0411: standard import "import argparse" should be placed before "import numpy as np" (wrong-import-order)
goprosync.py:3:0: W0611: Unused matplotlib.pyplot imported as plt (unused-import)

-----------------------------------
Your code has been rated at 6.34/10
```

2023-06-05 22:48 UTC, ntlhui commented on Gopro-Sync/goprosync.py
> +        exit()
Please use https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.suffix

2023-06-05 22:48 UTC, ntlhui commented on Gopro-Sync/goprosync.py
> +def gopro_sync(left, right, trimmed_left, trimmed_right):
Add type hints:
for example, `gopro_sync(left: Path, right: Path)`

2023-06-05 22:48 UTC, ntlhui commented on Gopro-Sync/README.md
> +python goprosync.py --left PATH_TO_LEFT_MP4 --right PATH_TO_RIGHT_MP4 --out PATH_TO_OUTPUT_DIRECTORY
Use the output from `python .\goprosync.py --help`

2023-06-05 22:48 UTC, ntlhui commented on Gopro-Sync/goprosync.py
> +        exit()
Maybe you should just create the directory?

2023-06-05 22:48 UTC, ntlhui commented on Gopro-Sync/goprosync.py
> +        pass
What happens if creating `.temp` fails because the system is unable to create `.temp`?

2023-07-11 21:17 UTC, closed without merging

2023-07-11 21:17 UTC, Xeanies commented
Fixed errors. Creating a new pull request.